{% set name = "pandora-geno" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tschuelia/Pandora/archive/{{ version }}.tar.gz
  sha256: f5d3131ed16f09fa851aac4ac2f139e21290b258ac8849316e5f98d13a45a152

build:
  entry_points:
    - pandora = pandora.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - pyarrow
    - plotly
    - scipy
    - pyyaml
    - scikit-learn >=1.0
    - pydantic >=2
    - python-kaleido
    - loguru
    - scikit-allel >=1.3.7
    - __unix

test:
  imports:
    - pandora
    - pandora.bootstrap
    - pandora.converter
    - pandora.custom_errors
    - pandora.custom_types
    - pandora.dataset
    - pandora.distance_metrics
    - pandora.embedding
    - pandora.embedding_comparison
    - pandora.imputation
    - pandora.pandora
    - pandora.plotting
    - pandora.sliding_window
  commands:
    - pip check
    - pandora --help
  requires:
    - pip

about:
  home: https://github.com/tschuelia/Pandora
  summary: Uncertainty estimation toolkit for dimensionality reduction on population genetics data.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
